  GNU nano 6.2                                    docker-compose.yml *                                           
version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: inventree_db
      POSTGRES_USER: inventree_user
      POSTGRES_PASSWORD: inventree_password
    networks:
      - inventree_network

  inventree:
    image: inventree/inventree:latest
    ports:
      - "8000:8000"
    environment:
      DB_NAME: inventree_db
      DB_USER: inventree_user
      DB_PASS: inventree_password
      DB_HOST: db
    networks:
      - inventree_network
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  inventree_network:
